In [7]:
# 1.1 Creating a Vector
import numpy as np

vector_row = np.array([1,2,3])

vector_column = np.array([[4],
                         [5],
                         [5]])

print(vector_row)
print(vector_column)

[1 2 3]
[[4]
 [5]
 [5]]


In [10]:
# 1.2 Creating a Matrix

matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(matrix)


[[1 2]
 [3 4]
 [5 6]]


In [11]:
# 1.3 Creating a Sparse Matrix
from scipy import sparse
 
matrix = np.array([[0, 0],
                    [1, 0],
                    [0, 2]])

print(matrix)

matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

[[0 0]
 [1 0]
 [0 2]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 0)	1
  (2, 1)	2


In [13]:
large_matrix = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

print(sparse.csr_matrix(large_matrix))

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [25]:
# 1.4 Preallocating Numpy Arrays

vector = np.zeros(shape=(2,2))
vector2 = np.zeros(shape=5)
vector3 = np.full(shape=(3,3) , fill_value=4)

print(vector,"\n\n",vector2 , "\n\n" , vector3)

[[0. 0.]
 [0. 0.]] 

 [0. 0. 0. 0. 0.] 

 [[4 4 4]
 [4 4 4]
 [4 4 4]]


In [49]:
# 1.5 Selecting Elements

vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(vector[3])
print(matrix[2,1])
print(vector[:])
print(vector[:3])
print(vector[3:])
print(vector[-1])
print(vector[-2])
print(vector[::-1])
print(vector[::2])
print("------\n",matrix[:2,:])
print("------\n",matrix[: ,1:2])

4
8
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
5
[6 5 4 3 2 1]
[1 3 5]
------
 [[1 2 3]
 [4 5 6]]
------
 [[2]
 [5]
 [8]]


In [59]:
# 1.6 Describing a Matrix
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 4)
12
2


In [62]:
# 1.7 Applying Functions over Each Element

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
add_100 = lambda i: i+100

vectorize_add100 = np.vectorize(add_100)
print(vectorize_add100(matrix))
print("---------------")
print(matrix + 200)

[[101 102 103]
 [104 105 106]
 [107 108 109]]
---------------
[[201 202 203]
 [204 205 206]
 [207 208 209]]


In [66]:
# 1.8 Finding the Maximum and Minimum Values
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(np.max(matrix))
print(np.min(matrix))
print(np.max(matrix, axis=0))
print(np.max(matrix , axis=1))


9
1
[7 8 9]
[3 6 9]


In [68]:
# 1.9 Calculating the Average, Variance, and Standard Deviation
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))
print(np.mean(matrix ,  axis=0))

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]


In [2]:
# 1.10 Reshaping Arrays
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
print(matrix.reshape(2,6) ,"\n")
print(matrix.reshape(1,12),"\n")
print(matrix.reshape(3,4),"\n")
print(matrix.reshape(6 , -1),"\n")
print(matrix.reshape(1 , -1),"\n")
print(matrix.reshape(-1 , 6),"\n")
print(matrix.reshape(12))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
