In [1]:
import numpy as np

In [2]:
# 1.11 Transposing a Vector or Matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                [7, 8, 9]])
print(matrix.T)
print(np.array([1,2,3,4,5]).T)
print(np.array([[1,2,3,4,5]]).T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [3]:
# 1.12 Flattening a Matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                [7, 8, 9]])

print(matrix.flatten())
print(matrix.reshape(1,-1))
print(matrix.ravel())
matrix_a = np.array([[11, 12],
                     [13, 14]])

matrix_b = np.array([[15, 16],
                     [17, 18]])
# to creat a list of matrix , matrix's dimension should be the same
matrix_list = [matrix_a , matrix_b]
print(np.ravel(matrix_list))

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18]


In [6]:
# 1.13 Finding the Rank of a Matrix
matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                [1, 1, 15]])
print(np.linalg.matrix_rank(matrix))

2


In [7]:
# 1.14 Getting the Diagonal of a Matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                [7, 8, 9]])

print(matrix.diagonal())
print(matrix.diagonal(offset=1))
print(matrix.diagonal(offset=-1))
# matrix a initialized above
print(matrix_a.diagonal(offset=1))

[1 5 9]
[2 6]
[4 8]
[12]


In [8]:
# 1.15 Calculating the Trace of a Matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                [7, 8, 9]])

print(matrix.trace())
print(sum(matrix.diagonal()))
print(sum(matrix[: , :1 ]))

15
15
[12]


In [ ]:
# 1.16 Calculating Dot Products
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
print(np.dot(vector_a,vector_b))
print(vector_a @ vector_b)

32
32
[[369 392]
 [433 460]]


In [14]:
# 1.17 Adding and Subtracting Matrices

matrix_a = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,2]])

matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])

print(np.add(matrix_a , matrix_b) , "\n")
print(np.subtract(matrix_a,matrix_b) , "\n")
print(matrix_a + matrix_b , "\n")
print(matrix_a * matrix_b ,"\n")
print(matrix_b ** 2)


[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]] 

[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]] 

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]] 

[[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]] 

[[ 1  9  1]
 [ 1  9  1]
 [ 1  9 64]]


In [17]:
# 1.18 Multiplying Matrices
matrix_a = np.array([[1, 1],
                    [1, 2]])

matrix_b = np.array([[1, 3],
                    [1, 2]])

print(np.dot(matrix_a, matrix_b),"\n")
print(matrix_a @ matrix_b , "\n")
print(matrix_a * matrix_b)

[[2 5]
 [3 7]] 

[[2 5]
 [3 7]] 

[[1 3]
 [1 4]]


In [20]:
# 1.19 Inverting a Matrix

matrix = np.array([[1, 4],
                   [2, 5]])

print(np.linalg.inv(matrix) , "\n")
print(matrix @ np.linalg.inv(matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]] 

[[1. 0.]
 [0. 1.]]


In [34]:
# 1.20 Generating Random Values
# this line repeat a set of generated random number
np.random.seed(0)

print(np.random.random(3))
print(np.random.randint(1,20,5))
print(np.random.normal(0 , 1 ,3))
print(np.random.logistic(0 , 1 ,3))
print(np.random.uniform(0 , 1 ,3))

[0.5488135  0.71518937 0.60276338]
[ 4  8 10 19  5]
[-0.29139398 -0.13309028 -0.1730696 ]
[ 1.46416405 -0.08013416 -0.4356214 ]
[0.83607876 0.33739616 0.64817187]
