In [ ]:
# Chapter 13. Linear Regression

In [ ]:
# Fitting a data
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features= 3,
                                   n_informative= 2,
                                   n_targets= 1,
                                   noise = 0.2,
                                   coef= False,
                                   random_state=1)

# create linear regression
regression = LinearRegression()

# train
model = regression.fit(features, target)

# View the intercept
model.intercept_

np.float64(-0.009650118178817557)

In [ ]:
# View the feature coefficients
model.coef_

array([1.95531234e-02, 4.42087450e+01, 5.81494563e+01])

In [3]:
# First value in the target vector
target[0]

np.float64(-20.870747595269407)

In [4]:
# Predict the target value of the first observation
model.predict(features)[0]

np.float64(-20.861927709296822)

In [5]:
model.score(features, target)

0.9999901732607787

In [6]:
# 13.2 Handling Interactive Effects
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features= 2,
                                   n_informative=2,
                                   n_targets=1,
                                   noise = 0.2 ,
                                   coef = False,
                                   random_state= 1)

# create infraction trm
interaction = PolynomialFeatures(degree= 3, include_bias=False , interaction_only= True)

features_interaction = interaction.fit_transform(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model  = regression.fit(features_interaction, target)

In [7]:
features[0]

array([0.0465673 , 0.80186103])

In [ ]:
import numpy as np

# For each observation, multiply the values of the first and second feature
interaction_term = np.multiply(features[: , 0], features[:, 1])

# View interaction term for first observation
interaction_term[0]

np.float64(0.037340501965846186)

In [9]:
# View the values of the first observation
features_interaction[0]

array([0.0465673 , 0.80186103, 0.0373405 ])

In [23]:
# 13.3 Fitting a Nonlinear Relationship

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features= 1,
                                   n_informative=1,
                                   n_targets= 1,
                                   noise = 0.2 ,
                                   coef = False,
                                   random_state= 1)

# Create polynomial features x^2 and x^3
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_polynomial, target)

# view first observation
features[0] 

array([-0.61175641])

In [ ]:
# View first observation raised to the second power, x^2
features[0] ** 2

array([0.37424591])

In [ ]:
# View first observation raised to the third power, x^3
features[0] ** 3

array([-0.22894734])

In [ ]:
# View the first observation's values for x, x^2, and x^3
features_polynomial[0]

array([-0.61175641,  0.37424591, -0.22894734])

In [40]:
# 13.4 Reducing Variance with Regularization

from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features= 3,
                                   n_informative=2,
                                   n_targets= 1,
                                   noise = 0.2 ,
                                   coef = False,
                                   random_state= 1)

# # Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create ridge regression with an alpha value
regression = Ridge(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_standardized, target)

model.coef_

array([-5.53808182e-03,  4.38955637e+01,  5.36603715e+01])

In [41]:
from sklearn.linear_model import RidgeCV

# Create ridge regression with three alpha values
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

# Fit the linear regression
model_cv = regr_cv.fit(features_standardized, target)

# view coefficient
model_cv.coef_

array([1.29223201e-02, 4.40972291e+01, 5.38979372e+01])

In [42]:
model_cv.alpha_

np.float64(0.1)

In [48]:
# 13.5 Reducing Features with Lasso Regression

from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features= 3,
                                   n_informative=2,
                                   n_targets= 1,
                                   noise = 0.2 ,
                                   coef = False,
                                   random_state= 1)
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create lasso regression with alpha value
regression = Lasso(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_standardized, target)

model.coef_

array([-0.        , 43.58618393, 53.39523724])

In [49]:

regression_alpha10 = Lasso(alpha=10)
model_alpha10 = regression_alpha10.fit(features_standardized, target)
model_alpha10.coef_

array([-0.        , 32.92181899, 42.73086731])