In [40]:
# Chapter 20. Tensors with PyTorch

In [41]:
# 20.1 Creating a Tensor

import torch
import numpy as np

# create a vector as a row
tensor_row = torch.tensor([1, 2, 3])

# create a vector as a column
tensor_column = torch.tensor([
    [1],
    [2],
    [3]
])

In [42]:
# 20.2 Creating a Tensor from NumPy

vector_row = np.array([1, 2, 3])
# Create a tensor from a NumPy array
tensor_row = torch.from_numpy(vector_row)

In [43]:
# 20.3 Creating a Sparse Tensor

# Create a tensor
tensor = torch.tensor([
                [0, 0],
                [0, 1],
                [3, 0]])

sparse_tensor = tensor.to_sparse()

print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [44]:
# 20.4 Selecting Elements in a Tensor

# Create vector tensor
vector = torch.tensor([1, 2, 3, 4, 5, 6])

matrix = torch.tensor([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])


In [45]:
# Select third element of vector
print(vector[2])
print(matrix[1,-1])
print(vector[:])
print(vector[:3])
print(vector[3:])
print(vector[-1])
print(matrix[:2 , :])
print(matrix[:,1:2])

tensor(3)
tensor(6)
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(6)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2],
        [5],
        [8]])


In [46]:
# Reverse the vector
vector[::-1]

ValueError: step must be greater than zero

In [ ]:
# Reverse the vector
vector.flip(dims=(-1,))

In [47]:
# 20.5 Describing a Tensor
import torch

# Create a tensor
tensor = torch.tensor([[1,2,3], [1,2,3]])

tensor.shape

torch.Size([2, 3])

In [48]:
# Get the data type of items in the tensor
tensor.dtype

torch.int64

In [49]:
# Get the layout of the tensor
tensor.layout

torch.strided

In [50]:
# Get the device being used by the tensor
tensor.device

device(type='cpu')

In [51]:
# 20.6 Applying Operations to Elements

# Create a tensor
tensor = torch.tensor([1, 2, 3])

tensor * 100

tensor([100, 200, 300])

In [52]:
# 20.7 Finding the Maximum and Minimum Values

# Create a tensor
torch.tensor([1,2,3])

print(tensor.max())

print(tensor.min())

# Create a multidimensional tensor
tensor = torch.tensor([[1,2,3],[1,2,5]])

print(tensor.max())

tensor(3)
tensor(1)
tensor(5)


In [56]:
# 20.8 Reshaping Tensors

# Create 4x3 tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])

tensor.reshape(2, 6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [57]:
# 20.9 Transposing a Tensor

# Create a two-dimensional tensor
tensor = torch.tensor([[[1,2,3]]])

# transpose it
tensor.mT

tensor([[[1],
         [2],
         [3]]])

In [58]:
tensor.permute(*torch.arange(tensor.ndim -1, -1, -1))

tensor([[[1]],

        [[2]],

        [[3]]])

In [59]:
# 20.10 Flattening a Tensor

# Create tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# flatten tensor
tensor.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# 20.11 Calculating Dot Products

# Create one tensor
tensor_1 = torch.tensor([1, 2, 3])

# Create second tensor
tensor_2 = torch.tensor([4, 5, 6])

tensor_1.dot(tensor_2)

tensor(32)

In [61]:
# 20.12 Multiplying Tensors

# Create one tensor
tensor_1 = torch.tensor([1, 2, 3])

# Create second tensor
tensor_2 = torch.tensor([4, 5, 6])

tensor_1 * tensor_2

tensor([ 4, 10, 18])

In [62]:
tensor_1 + tensor_2

tensor([5, 7, 9])

In [63]:
tensor_1 - tensor_2

tensor([-3, -3, -3])

In [64]:
tensor_1 / tensor_2

tensor([0.2500, 0.4000, 0.5000])