In [19]:
# handling text

# 6.1 cleaning text
# create a text

text_data = ["   Interrobang. By Aishwarya Henriette     " ,
             "Parking And Going. By Karl Gautier",
             " Today Is The night. By Jarek Prakash     "]


# strip white spaces
strip_whitespace = [string.strip() for string in text_data]

strip_whitespace

['Interrobang. By Aishwarya Henriette',
 'Parking And Going. By Karl Gautier',
 'Today Is The night. By Jarek Prakash']

In [20]:
# remove periods
remove_periods = [string.replace(".", "") for string in strip_whitespace]
remove_periods

['Interrobang By Aishwarya Henriette',
 'Parking And Going By Karl Gautier',
 'Today Is The night By Jarek Prakash']

In [21]:
# create function

def capitalizer(string : str) -> str:
    return string.upper()

# apply function
[capitalizer(string) for string in remove_periods]

['INTERROBANG BY AISHWARYA HENRIETTE',
 'PARKING AND GOING BY KARL GAUTIER',
 'TODAY IS THE NIGHT BY JAREK PRAKASH']

In [22]:
# import library
import re

# create a function
def replace_letters_with_X(string: str) -> str:
    return re.sub(r"[a-zA-Z]" , "X" , string)

# apply function
[replace_letters_with_X(string) for string in remove_periods]

['XXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX',
 'XXXXXXX XXX XXXXX XX XXXX XXXXXXX',
 'XXXXX XX XXX XXXXX XX XXXXX XXXXXXX']

In [23]:
# define a string
s = "machine learning in python cookbook"

# find the first index of letter "n"
find_n = s.find("n")

# Whether or not the string starts with "m"
starts_with_m = s.startswith("m")  # True

# Whether or not the string ends with "python"
ends_with_python = s.endswith("python")  # output : False

# Is the string alphanumeric
is_alnum = s.isalnum()

# Is it composed of only alphabetical characters (not including spaces)
is_alpha = s.isalpha()

# encode as utf-8
encode_as_utf8 = s.encode("utf-8")

decode = encode_as_utf8.decode("utf-8")

print(
    find_n,
    starts_with_m,
    ends_with_python,
    is_alnum,
    is_alpha,
    encode_as_utf8,
    decode,
    sep = "|"
)

5|True|False|False|False|b'machine learning in python cookbook'|machine learning in python cookbook


In [24]:
# 6.2 Parsing and Cleaning HTML
from bs4 import BeautifulSoup

html = "<div class='full_name'>"\
        "<span style='font-weight:bold'>Masego"\
        "</span> Azra</div>"

# parse html
soup = BeautifulSoup(html , "lxml")

#  Find the div with the class "full_name", show text
soup.find("div" , {"class" : "full_name"}).text

'Masego Azra'

In [25]:
# 6.3 Removing Punctuation

import unicodedata
import sys

# create  text
text_data =['Hi!!!! I. Love. This. Song....',
            '10000% Agree!!!! #LoveIT',
            'Right?!?!']

# create a dictionary of punctuation characters
punctuation = dict.fromkeys(
    (i for i in range(sys.maxunicode)
    if unicodedata.category(chr(i)).startswith('P')
    ),
    None
)

#  translate all punctuation characters in text to none
[string.translate(punctuation) for string in text_data]

['Hi I Love This Song', '10000 Agree LoveIT', 'Right']

In [26]:
# Uninstall and reinstall NLTK to ensure a clean installation
# %pip uninstall -y nltk
# %pip install nltk

# Import NLTK and download required resources
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to /home/hadisasadi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/hadisasadi/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [27]:
from nltk.tokenize import word_tokenize

string = "The science of today is the technology of tomorrow"
tokens = word_tokenize(string)
tokens

['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [28]:
from nltk.tokenize import sent_tokenize

string = "The science of today is the technology of tomorrow. Tomorrow is today."

sent_tokenize(string)

['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

In [29]:
# 6.5 Removing Stop Words
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/hadisasadi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
# create word tokens
tokenized_words  =  ['i',
                    'am',
                    'going',
                    'to',
                    'go',
                    'to',
                    'the',
                    'store',
                    'and',
                    'park']

# load stop words
stop_words = stopwords.words('english')

#remove stop words
[word for word in tokenized_words if word not in stop_words]

['going', 'go', 'store', 'park']

In [31]:
# show stop words
stop_words[:6]

['a', 'about', 'above', 'after', 'again', 'against']

In [32]:
# 6.6 Stemming Words
from nltk.stem.porter import PorterStemmer

# Create word tokens
tokenized_words = ['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']

# create stemmer
porter = PorterStemmer()

# apply stemmer
[porter.stem(word) for word in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

In [34]:
import nltk
from nltk import pos_tag
from nltk import word_tokenize
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
# Download required NLTK data with error handling
try:
    nltk.download('punkt')  # For word_tokenize
    nltk.download('punkt_tab')  # For tokenizer in newer NLTK versions
    nltk.download('averaged_perceptron_tagger', quiet=False)  # For pos_tag, show download progress
except Exception as e:
    print(f"Error downloading NLTK data: {e}")

# Verify NLTK data path (optional, for debugging)
print("NLTK data path:", nltk.data.path)

# Create text
text_data = "Chris loved outdoor running"

# Use pretrained part of speech tagger
tokens = word_tokenize(text_data)
text_tagged = pos_tag(tokens)

# Print the result
print(text_tagged)

[nltk_data] Downloading package punkt to /home/hadisasadi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/hadisasadi/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/hadisasadi/nltk_data...


[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt to /home/hadisasadi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/hadisasadi/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/hadisasadi/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


NLTK data path: ['/home/hadisasadi/nltk_data', '/home/hadisasadi/myenv/nltk_data', '/home/hadisasadi/myenv/share/nltk_data', '/home/hadisasadi/myenv/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']
[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]


In [35]:
from sklearn.preprocessing import MultiLabelBinarizer
import nltk
from nltk import pos_tag
from nltk import word_tokenize

# Create text
tweets = ["I am eating a burrito for breakfast",
          "Political science is an amazing field",
          "San Francisco is an awesome city"]

tagged_tweets = []
# Tag each word and each tweet
for tweet in tweets:
    tweet_tag = nltk.pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word,tag in tweet_tag])

In [17]:
# Use one-hot encoding to convert the tags into features

one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)

array([], shape=(0, 0), dtype=int64)

In [36]:
# 6.8 Performing Named-Entity Recognition

import spacy

# load the spacy package and use it to parse the text
nlp = spacy.load("en_core_web_sm")
doc = nlp("Elon Musk offered to buy Twitter using $21B of his own money.")

# print each entity
print(doc.ents)

# # For each entity print the text and the entity label

for entity in doc.ents:
    print(entity.text, entity.label , sep=", ")

(Elon Musk, Twitter, 21B)
Elon Musk, 380
Twitter, 380
21B, 394


In [37]:
# 6.9 Encoding Text as a Bag of Words

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# create text
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

# Create the bag of words feature matrix
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

# show feature of matrix
print(bag_of_words)

bag_of_words.toarray()

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (3, 8)>
  Coords	Values
  (0, 6)	1
  (0, 3)	2
  (1, 7)	1
  (1, 5)	1
  (1, 1)	1
  (2, 4)	1
  (2, 0)	1
  (2, 2)	1


array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]])

In [38]:
# show feature names

count.get_feature_names_out()

array(['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love',
       'sweden'], dtype=object)

In [39]:
# create feature matrix with arguments

count_2gram = CountVectorizer(ngram_range = (1,2),
                              stop_words= "english",
                              vocabulary=['brazil'])

bag = count_2gram.fit_transform(text_data)

# view feature matrix
print(bag.toarray())

# view the 1_grams and 2_grams
count_2gram.vocabulary_

[[2]
 [0]
 [0]]


{'brazil': 0}

In [40]:
# 6.10 Weighting Word Importance

import numpy as np

# frequency inverse document frequency (tf-idf)
from sklearn.feature_extraction.text import  TfidfVectorizer

# create text
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

# Create the tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

print(feature_matrix)

feature_matrix.toarray()

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (3, 8)>
  Coords	Values
  (0, 6)	0.4472135954999579
  (0, 3)	0.8944271909999159
  (1, 7)	0.5773502691896257
  (1, 5)	0.5773502691896257
  (1, 1)	0.5773502691896257
  (2, 4)	0.5773502691896257
  (2, 0)	0.5773502691896257
  (2, 2)	0.5773502691896257


array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [41]:
tfidf.vocabulary_

{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

In [42]:
# 6.11 Using Text Vectors to Calculate Text Similarity in a Search Query

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# create a searchable text data
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

# create a tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

# create a search query and transform it into a tf idf vector
text = "Brazil is the best"
vector = tfidf.transform([text])

# Calculate the cosine similarities between the input vector and all other vectors
cosine_similarities = linear_kernel(vector,feature_matrix).flatten()

# Get the index of the most relevent items in order
related_doc_indicies = cosine_similarities.argsort()[ : :-1]

[(text_data[i], cosine_similarities[i]) for i in related_doc_indicies]

[(np.str_('Sweden is best'), np.float64(0.6666666666666666)),
 (np.str_('I love Brazil. Brazil!'), np.float64(0.5163977794943222)),
 (np.str_('Germany beats both'), np.float64(0.0))]

In [43]:
vector.toarray()

array([[0.        , 0.57735027, 0.        , 0.57735027, 0.        ,
        0.57735027, 0.        , 0.        ]])

In [44]:
related_doc_indicies

array([1, 0, 2])

In [49]:
# 6.12 Using a Sentiment Analysis Classifier

from transformers import  pipeline

classifier = pipeline("sentiment-analysis", framework="pt")

# classify some text
sentiment_1 = classifier("I hate machine learning! It's the absolute worst.")
sentiment_2 = classifier("Machine learning is the absolute"
"bees knees I love it so much!")

print(sentiment_1 , sentiment_2)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'NEGATIVE', 'score': 0.9998020529747009}] [{'label': 'POSITIVE', 'score': 0.9995730519294739}]
